migrate to microprofile
AbdelSBIHI/Everis-Car-APP-API pull request #20
Opened 2021-03-08 15:20 UTC by AbdelSBIHI

2021-03-08 15:34 UTC, darkjeffbr requested changes

2021-03-08 15:34 UTC, darkjeffbr commented on pom.xml
> +            <groupId>io.openliberty</groupId>
I see that you're using openliberty, but we should try to use payara micro. Could you please give it a try with payara micro ?

2021-03-09 12:28 UTC, AbdelSBIHI commented
i don't know if that plugin is enough to deploy the api in payara micro i have a very bad connection the api take to mush time to build

2021-03-09 13:23 UTC, darkjeffbr approved these changes

2021-03-09 13:23 UTC, merged